import { expect, test, type Page, type Route } from '@playwright/test'

const wordStats = { known_count: 0, unknown_count: 0, skipped_count: 0, total_attempts: 0, accuracy: null, consecutive_known: 0, consecutive_unknown: 0, last_status: null, last_reviewed_at: null, last_effective_status: null, last_effective_reviewed_at: null, interval_days: 0, due_at: null }
const envelope = <T>(data: T, meta: Record<string, unknown> = {}) => ({ code: 'OK', message: 'success', data, meta, request_id: 'phase4-e2e' })
const items = Array.from({ length: 24 }, (_, index) => ({
  item_id: 101 + index, position: index + 1, word_id: index + 1,
  word: { en_word: index === 0 ? 'focus' : index === 1 ? 'C++' : `word-${index + 1}`, phonetic: `/word${index + 1}/`, cn_meaning: index === 0 ? '<img src=x onerror=alert(1)>' : `第 ${index + 1} 个释义`, example_sentence: index === 0 ? 'Focus on the task.' : index === 1 ? 'I use C++ daily.' : `A sentence with word-${index + 1} inside.` },
  source_categories: index % 2 ? ['due'] : ['new', 'custom'], reason: `入选原因 ${index + 1}`, latest_review_log_id: null,
}))
const strategy = { new_words_limit: 10, error_words_limit: 5, due_words_limit: 5, custom_words_limit: 5, fallback_unreviewed_days: 3 }
const baseSession = { session_id: 5, status: 'active', strategy_version: 'v4', seed: 42, strategy_params: strategy, requested_counts: { new: 10, error: 5, due: 5, custom: 5 }, actual_counts: { unique_total: 24, new: 10, error: 8, due: 10, custom: 4 }, created_by_actor_type: 'api_client', created_by_actor_id: 'skill-client', skill_name: 'Print Helper', skill_version: '2.0', version: 1, generated_at: '2026-07-20T01:00:00Z', printed_at: null, completed_at: null, archived_at: null, items, rounds: [] }
const round = { round_id: 9, session_id: 5, mode: 'offline', status: 'active', version: 1, started_at: '2026-07-20T02:00:00Z', completed_at: null, item_total: 24, answered_count: 0 }
const review = (itemId: number, status: string, version = 1) => ({ id: itemId + 900, word_id: itemId - 100, session_item_id: itemId, review_round_id: 9, status, source: 'print_manual', actor_type: 'web_user', actor_id: 'local', client_event_id: `event-${itemId}`, duration_ms: null, reviewed_at: '2026-07-20T02:00:00Z', version, created_at: '2026-07-20T02:00:00Z', updated_at: version > 1 ? '2026-07-20T03:00:00Z' : '2026-07-20T02:00:00Z', stats: wordStats })

async function installPhase4Api(page: Page, options: { conflictOnce?: boolean; failBatchOnce?: boolean; failGenerateOnce?: boolean; emptyGenerate?: boolean } = {}) {
  let session = structuredClone(baseSession); let savedReviews: ReturnType<typeof review>[] = []; let batchCalls = 0; let printCalls = 0; let generated = 0; const generationKeys:string[]=[];const generationPayloads:Record<string,unknown>[]=[]
  await page.addInitScript(() => { Object.defineProperty(window, 'print', { value: () => { (window as unknown as { __printed:number }).__printed = ((window as unknown as { __printed:number }).__printed || 0) + 1 }, configurable: true }) })
  await page.route('**/api/v1/**', async (route: Route) => {
    const request=route.request();const url=new URL(request.url());const path=url.pathname;const method=request.method()
    if(path==='/api/v1/auth/me'&&method==='GET')return route.fulfill({json:envelope({username:'admin',role:'admin'})})
    if(path==='/api/v1/capabilities')return route.fulfill({json:envelope({api_version:'v1',server_time:'2026-07-20T00:00:00Z',server_timezone:'Asia/Shanghai',review_statuses:['known','unknown','skipped'],review_modes:['offline','online'],max_import_bytes:10485760,max_import_rows:10000,max_practice_words:50,max_batch_results:200,idempotency_retention_days:30,features:{batch_results:true}})})
    if(path==='/api/v1/words'&&method==='GET')return route.fulfill({json:envelope(items.map(item=>({id:item.word_id,en_word:item.word.en_word,normalized_en_word:item.word.en_word.toLowerCase(),phonetic:item.word.phonetic,cn_meaning:item.word.cn_meaning,example_sentence:item.word.example_sentence,is_custom:false,tags:[],version:1,created_at:'2026-07-20T01:00:00Z',updated_at:'2026-07-20T01:00:00Z',deleted_at:null,stats:wordStats})),{page:1,size:100,total:items.length})})
    if(path==='/api/v1/practice-sessions'&&method==='GET')return route.fulfill({json:envelope([session],{page:1,size:50,total:1})})
    if(path==='/api/v1/daily-table/generate'&&method==='POST'){generated++;generationKeys.push(request.headers()['idempotency-key']);generationPayloads.push(JSON.parse(request.postData()||'{}'));expect(generationKeys.at(-1)).toBeTruthy();if(options.failGenerateOnce&&generated===1)return route.fulfill({status:503,json:{code:'UNAVAILABLE',message:'temporary failure',details:[],request_id:'generate-failure'}});const generatedSession=options.emptyGenerate?{...session,items:[],actual_counts:{unique_total:0,new:0,error:0,due:0,custom:0}}:session;return route.fulfill({status:201,json:envelope({...generatedSession,web_url:'/daily/sessions/5',print_url:'/daily/sessions/5?view=print'})})}
    if(path==='/api/v1/practice-sessions/5'&&method==='GET')return route.fulfill({json:envelope(session)})
    if(path==='/api/v1/practice-sessions/5/printed'&&method==='POST'){printCalls++;session={...session,printed_at:'2026-07-20T04:00:00Z',version:2};return route.fulfill({json:envelope({...session,items:undefined,rounds:undefined})})}
    if(path==='/api/v1/practice-sessions/5/review-rounds'&&method==='POST'){session={...session,rounds:[round]};return route.fulfill({status:201,json:envelope(round)})}
    if(path==='/api/v1/reviews'&&method==='GET')return route.fulfill({json:envelope(savedReviews,{page:1,size:100,total:savedReviews.length})})
    if(path==='/api/v1/practice-review-rounds/9/results'&&method==='PUT'){
      batchCalls++;const body=JSON.parse(request.postData()||'{}');if(options.failBatchOnce&&batchCalls===1)return route.fulfill({status:503,json:{code:'UNAVAILABLE',message:'temporary failure',details:[],request_id:'batch-failure'}})
      if(options.conflictOnce&&batchCalls===1){savedReviews=[review(body.items[0].item_id,'unknown',2)];return route.fulfill({status:409,json:{code:'VERSION_CONFLICT',message:'review was modified',details:[{item_id:body.items[0].item_id,current_version:2}],request_id:'conflict'}})}
      const changed=body.items.map((entry:{item_id:number;status:string;expected_version?:number})=>review(entry.item_id,entry.status,(entry.expected_version||0)+1));for(const item of changed){savedReviews=savedReviews.filter(existing=>existing.session_item_id!==item.session_item_id);savedReviews.push(item)}if(savedReviews.length===24)session={...session,completed_at:'2026-07-20T03:00:00Z'}
      return route.fulfill({json:envelope({round:{...round,answered_count:savedReviews.length,status:savedReviews.length===24?'completed':'active'},items:changed})})
    }
    return route.fulfill({status:404,json:{code:'NOT_FOUND',message:'not found',details:[],request_id:'phase4-404'}})
  })
  return { get batchCalls(){return batchCalls},get printCalls(){return printCalls},get generated(){return generated},get reviews(){return savedReviews},get generationKeys(){return generationKeys},get generationPayloads(){return generationPayloads} }
}

test('strategy generation supports total count with proportional weights',async({page})=>{const api=await installPhase4Api(page);await page.goto('/daily/generate');await expect(page.locator('.estimate strong')).toHaveText('25');await page.locator('.total-mode-row .el-switch').click();await page.getByRole('button',{name:'生成并打开'}).click();await expect(page).toHaveURL(/daily\/sessions\/5/);expect(api.generated).toBe(1);expect(api.generationPayloads[0]).toMatchObject({new_words_limit:10,error_words_limit:5,due_words_limit:5,custom_words_limit:5,total_words:25})})

test('custom generation sends only explicitly selected word ids',async({page})=>{const api=await installPhase4Api(page);await page.goto('/daily/generate');await page.getByText('自定义单词',{exact:true}).click();const selector=page.locator('.selection-field .el-select');await selector.click();const options=page.locator('.el-select-dropdown:visible .el-select-dropdown__item');await options.nth(0).click();await options.nth(1).click();await page.keyboard.press('Escape');await page.getByRole('button',{name:'生成并打开'}).click();await expect(page).toHaveURL(/daily\/sessions\/5/);expect(api.generationPayloads[0].word_ids).toEqual([1,2]);expect(api.generationPayloads[0].new_words_limit).toBe(0)})

test('generation retry reuses its idempotency key and empty candidates stay actionable',async({page})=>{const retryApi=await installPhase4Api(page,{failGenerateOnce:true});await page.goto('/daily/generate');await page.getByRole('button',{name:'生成并打开'}).click();await expect(page.getByText(/temporary failure/)).toBeVisible();await page.getByRole('button',{name:'生成并打开'}).click();await expect(page).toHaveURL(/daily\/sessions\/5/);expect(retryApi.generationKeys[1]).toBe(retryApi.generationKeys[0]);await page.unrouteAll();await installPhase4Api(page,{emptyGenerate:true});await page.goto('/daily/generate');await page.getByRole('button',{name:'生成并打开'}).click();await expect(page.getByText('当前策略没有找到候选单词。可增加词库、降低限制或稍后再试。')).toBeVisible();await expect(page).toHaveURL(/daily\/generate/)})

test('only the selected worksheet tab is printed with the redesigned A4 layout',async({page})=>{const api=await installPhase4Api(page);await page.goto('/daily/sessions/5?view=print');await expect(page.getByText('外部 Skill · Print Helper')).toBeVisible();expect(await page.locator('.print-question img').count()).toBe(0);await expect(page.getByText('打印时附答案页')).toHaveCount(0);await expect(page.locator('.print-container')).not.toContainText('会话 #');const questionNumbers=await page.locator('.print-question tbody .number-cell').allTextContents();await page.emulateMedia({media:'print'});expect(await page.locator('.print-question').evaluate(element=>getComputedStyle(element).display)).not.toBe('none');expect(await page.locator('.print-answer').evaluate(element=>getComputedStyle(element).display)).toBe('none');await page.emulateMedia({media:'screen'});await page.getByRole('tab',{name:'答案'}).click();const answerNumbers=await page.locator('.print-answer tbody .number-cell').allTextContents();expect(answerNumbers).toEqual(questionNumbers);await page.getByRole('button',{name:/打印当前答案/}).click();await page.getByRole('button',{name:'确认已完成打印'}).click();expect(api.printCalls).toBe(1);expect(await page.evaluate(()=>(window as unknown as {__printed:number}).__printed)).toBe(1);await page.emulateMedia({media:'print'});expect(await page.locator('.sidebar').evaluate(element=>getComputedStyle(element).display)).toBe('none');expect(await page.locator('.print-question').evaluate(element=>getComputedStyle(element).display)).toBe('none');expect(await page.locator('.print-answer').evaluate(element=>getComputedStyle(element).display)).not.toBe('none');expect(await page.locator('.worksheet-table thead').last().evaluate(element=>getComputedStyle(element).display)).toBe('table-header-group');expect(await page.locator('.worksheet-table tbody tr').last().evaluate(element=>getComputedStyle(element).breakInside)).toBe('avoid')})

test('offline batch results persist across refresh and permit corrections',async({page})=>{const api=await installPhase4Api(page);await page.goto('/daily/sessions/5');await page.getByRole('button',{name:'开始结果回录'}).first().click();await page.getByRole('tab',{name:'结果回录'}).click();const mobile=page.viewportSize()!.width<640;if(mobile){await page.getByRole('button',{name:/^认识/}).click();await page.getByRole('button',{name:/下一题/}).click();await page.getByRole('button',{name:/^跳过/}).click()}else{const selectors=page.locator('.desktop-recorder:visible .result-selector');await selectors.nth(0).getByRole('button',{name:/^认识/}).click();await selectors.nth(1).getByRole('button',{name:/^跳过/}).click()}await page.getByRole('button',{name:'批量保存本轮结果'}).click();await expect(page.getByText('已保存 2 / 24')).toBeVisible();expect(api.batchCalls).toBe(1);await page.reload();await page.getByRole('tab',{name:'结果回录'}).click();await expect(page.getByText('已保存 2 / 24')).toBeVisible();if(mobile){await page.getByRole('button',{name:/^不认识/}).click()}else{await page.locator('.desktop-recorder:visible .result-selector').nth(0).getByRole('button',{name:/^不认识/}).click()}await page.getByRole('button',{name:'批量保存本轮结果'}).click();expect(api.batchCalls).toBe(2);expect(api.reviews.find(item=>item.session_item_id===101)?.status).toBe('unknown')})

test('completing result entry shows the session as completed',async({page})=>{await installPhase4Api(page);await page.goto('/daily/sessions/5');await page.getByRole('button',{name:'开始结果回录'}).first().click();await page.getByRole('tab',{name:'结果回录'}).click();await page.getByRole('button',{name:'全部认识'}).click();await expect(page.locator('.session-summary')).toContainText('已完成')})

test('409 conflict reloads server state and offers an explicit resolution',async({page})=>{const api=await installPhase4Api(page,{conflictOnce:true});await page.goto('/daily/sessions/5');await page.getByRole('button',{name:'开始结果回录'}).first().click();await page.getByRole('tab',{name:'结果回录'}).click();const selector=page.viewportSize()!.width<640?page.locator('.mobile-recorder:visible .result-selector'):page.locator('.desktop-recorder:visible .result-selector').first();await selector.getByRole('button',{name:/^认识/}).click();await page.getByRole('button',{name:'批量保存本轮结果'}).click();await page.getByRole('button',{name:'采用服务器最新值'}).click();await expect(page.getByText('已采用服务器中的最新结果。')).toBeVisible();expect(api.batchCalls).toBe(1)})

test('network failure preserves unsaved offline selections for retry',async({page})=>{const api=await installPhase4Api(page,{failBatchOnce:true});await page.goto('/daily/sessions/5');await page.getByRole('button',{name:'开始结果回录'}).first().click();await page.getByRole('tab',{name:'结果回录'}).click();const selector=page.viewportSize()!.width<640?page.locator('.mobile-recorder:visible .result-selector'):page.locator('.desktop-recorder:visible .result-selector').first();await selector.getByRole('button',{name:/^认识/}).click();await page.getByRole('button',{name:'批量保存本轮结果'}).click();await expect(page.getByText(/保存失败，您的选择仍保留/)).toBeVisible();await expect(page.getByText('待保存 1 项')).toBeVisible();await page.getByRole('button',{name:'批量保存本轮结果'}).click();await expect(page.getByText('已保存 1 / 24')).toBeVisible();expect(api.batchCalls).toBe(2)})
