<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useRouter } from 'vue-router'
import AsyncState from '@/components/AsyncState.vue'
import { getCapabilities } from '@/api/capabilities'
import { deleteSession, generateSession, listSessions, updateSession } from '@/api/practiceSessions'
import { newEventId, normalizeApiError } from '@/api/client'
import { listWords } from '@/api/words'
import { useAsyncState } from '@/composables/useAsyncState'
import type { PracticeSession, StrategyRequest, Word } from '@/types/domain'

type GeneratePhase = 'editing' | 'validating' | 'generating' | 'ready' | 'empty' | 'error'
const router=useRouter();const state=useAsyncState<PracticeSession[]>([]);const total=ref(0);const maxPracticeWords=ref(200);const phase=ref<GeneratePhase>('editing');const generateError=ref('');const generationKey=ref<string|null>(null)
const mode=ref<'strategy'|'selection'>('strategy');const wordOptions=ref<Word[]>([]);const wordsLoading=ref(false)
const form=reactive<StrategyRequest>({new_words_limit:10,error_words_limit:15,due_words_limit:20,custom_words_limit:5,fallback_unreviewed_days:3,word_ids:[]})
const estimatedTotal=computed(()=>mode.value==='selection'?form.word_ids.length:form.new_words_limit+form.error_words_limit+form.due_words_limit+form.custom_words_limit)
const invalidReason=computed(()=>estimatedTotal.value===0?'请至少选择 1 个单词。':estimatedTotal.value>maxPracticeWords.value?`预计总量不能超过 ${maxPracticeWords.value}。`:null)
const presets=[{label:'轻量 15',values:[5,5,5,0]},{label:'标准 50',values:[10,15,20,5]},{label:'重点错词',values:[5,30,10,5]}]
async function load(){await state.run(async signal=>{const [sessions,capabilities]=await Promise.all([listSessions(1,50,signal),getCapabilities(signal).catch(()=>null)]);total.value=Number(sessions.meta.total||0);if(capabilities)maxPracticeWords.value=capabilities.max_practice_words;return sessions.data}).catch(()=>{});await searchWords('')}
async function searchWords(keyword:string){wordsLoading.value=true;try{const result=await listWords({page:1,size:100,keyword:keyword.trim()||undefined,sort:'en_word_asc'});const selected=new Set(form.word_ids);wordOptions.value=[...wordOptions.value.filter(word=>selected.has(word.id)),...result.data.filter(word=>!selected.has(word.id))].filter((word,index,all)=>all.findIndex(item=>item.id===word.id)===index)}catch{}finally{wordsLoading.value=false}}
function applyPreset(values:number[]){[form.new_words_limit,form.error_words_limit,form.due_words_limit,form.custom_words_limit]=values}
async function generate(){phase.value='validating';generateError.value='';if(invalidReason.value){generateError.value=invalidReason.value;phase.value='error';return}phase.value='generating';generationKey.value ||= newEventId();const payload={...form,word_ids:mode.value==='selection'?[...form.word_ids]:[]};if(mode.value==='selection')Object.assign(payload,{new_words_limit:0,error_words_limit:0,due_words_limit:0,custom_words_limit:0});try{const session=await generateSession(payload,undefined,generationKey.value);const actual=session.items?.length||0;if(actual===0){phase.value='empty';generateError.value='当前策略没有找到候选单词。可增加词库、降低限制或稍后再试。';generationKey.value=null;await load();return}phase.value='ready';generationKey.value=null;ElMessage.success(`已生成 ${actual} 个词的复习表`);await router.push(`/daily/sessions/${session.session_id}`)}catch(e){const error=normalizeApiError(e);phase.value='error';generateError.value=error.message+(error.requestId?`（请求编号 ${error.requestId}）`:'')}}
const count=(session:PracticeSession)=>Object.values(session.actual_counts).reduce((sum,value)=>sum+Number(value||0),0)
const editOpen=ref(false);const editing=ref<PracticeSession|null>(null);const editForm=reactive({title:'',note:''});const editSaving=ref(false);const editError=ref('');const removing=ref<number|null>(null)
function openEdit(s:PracticeSession){editing.value=s;editForm.title=s.title||'';editForm.note=s.note||'';editError.value='';editOpen.value=true}
async function saveEdit(){if(!editing.value)return;editSaving.value=true;editError.value='';try{await updateSession(editing.value.session_id,{title:editForm.title.trim()||null,note:editForm.note.trim()||null,expected_version:editing.value.version});ElMessage.success('已保存');editOpen.value=false;await load()}catch(e){const err=normalizeApiError(e);editError.value=err.isConflict?'复习表已被其他操作修改，请关闭后重试。':err.message}finally{editSaving.value=false}}
async function removeSession(s:PracticeSession){try{await ElMessageBox.confirm(`确定删除复习表 #${s.session_id}${s.title?`「${s.title}」`:''}吗？其题目、轮次和回录流水都会一并删除，相关单词统计会重建，且不可恢复。`,'确认删除',{confirmButtonText:'删除',cancelButtonText:'取消',type:'warning'});removing.value=s.session_id;await deleteSession(s.session_id,s.version);ElMessage.success('已删除');await load()}catch(e){if(e==='cancel'||e==='close')return;const err=normalizeApiError(e);ElMessage.error(err.isConflict?'数据已变化，请刷新后重试':err.message)}finally{removing.value=null}}
watch([form,mode],()=>{if(phase.value!=='generating')phase.value='editing';generationKey.value=null;generateError.value=''},{deep:true});onMounted(load)
</script>
<template><section class="page"><div class="page-heading"><div><p class="eyebrow">PRACTICE SHEETS</p><p>按新词、错词、到期词和自定义词生成可解释、可复现的复习表。</p></div></div>
  <div class="generate-grid"><form class="panel strategy-form" @submit.prevent="generate"><div class="strategy-title"><div><h2>生成一张复习表</h2><p class="muted">同一单词只出现一次。某类词不足时，按「错词→新词→到期词→自定义词」从其他类别补足，总数尽量凑满。</p></div><div class="estimate"><strong>{{ estimatedTotal }}</strong><span>预计上限 / {{ maxPracticeWords }}</span></div></div>
    <el-radio-group v-model="mode" aria-label="复习表生成方式"><el-radio-button value="strategy">按策略选词</el-radio-button><el-radio-button value="selection">自定义单词</el-radio-button></el-radio-group>
    <template v-if="mode==='strategy'"><div class="mobile-presets" aria-label="数量预设"><button v-for="preset in presets" :key="preset.label" type="button" @click="applyPreset(preset.values)">{{ preset.label }}</button></div>
    <div class="quota-grid"><div class="quota-field"><label>新词</label><el-slider v-model="form.new_words_limit" :min="0" :max="100"/><el-input-number v-model="form.new_words_limit" :min="0" :max="100"/></div><div class="quota-field"><label>错词</label><el-slider v-model="form.error_words_limit" :min="0" :max="100"/><el-input-number v-model="form.error_words_limit" :min="0" :max="100"/></div><div class="quota-field"><label>到期词</label><el-slider v-model="form.due_words_limit" :min="0" :max="100"/><el-input-number v-model="form.due_words_limit" :min="0" :max="100"/></div><div class="quota-field"><label>自定义词</label><el-slider v-model="form.custom_words_limit" :min="0" :max="100"/><el-input-number v-model="form.custom_words_limit" :min="0" :max="100"/></div></div></template>
    <div v-else class="selection-field"><label for="custom-word-select">选择本次复习表中的全部单词</label><el-select id="custom-word-select" v-model="form.word_ids" multiple filterable remote reserve-keyword :remote-method="searchWords" :loading="wordsLoading" placeholder="输入英文或中文搜索，最多选择 200 个" aria-label="自定义复习单词"><el-option v-for="word in wordOptions" :key="word.id" :value="word.id" :label="`${word.en_word} · ${word.cn_meaning}`"/></el-select><small>生成顺序与选择顺序一致；不会混入策略候选词。</small></div>
    <div class="advanced-row"><el-form-item label="未复习兜底天数"><el-input-number v-model="form.fallback_unreviewed_days" :min="1" :max="365"/></el-form-item><el-form-item label="随机种子（可选）"><el-input-number v-model="form.seed" :min="0" :max="2147483647" placeholder="自动生成"/></el-form-item></div>
    <div v-if="generateError" :class="phase==='empty'?'empty-notice':'error-box'" role="alert">{{ generateError }}</div><el-button native-type="submit" type="primary" size="large" :loading="phase==='generating'" :disabled="Boolean(invalidReason)">生成并打开</el-button></form>
    <article class="panel"><p class="eyebrow">HOW IT WORKS</p><h2>纸面为主，网页辅助</h2><ol class="steps"><li><span>1</span><div><strong>生成</strong><p>系统保存策略、随机种子、题目快照和入选原因。</p></div></li><li><span>2</span><div><strong>打印复习</strong><p>选择题型，打印复习表和可选答案页。</p></div></li><li><span>3</span><div><strong>结果回录</strong><p>每次线下复习创建新轮次，批量保存三态结果。</p></div></li></ol></article></div>
  <article class="panel"><div class="section-title"><div><p class="eyebrow">ALL SESSIONS</p><h2>历史复习表 <small>{{ total }}</small></h2></div><el-button :loading="state.loading.value" @click="load">刷新</el-button></div><AsyncState :phase="state.phase.value" :error="state.error.value" empty-text="还没有复习表。" @retry="load"><div class="session-grid"><RouterLink v-for="session in state.data.value" :key="session.session_id" class="session-card" :to="`/daily/sessions/${session.session_id}`"><div class="session-head"><strong>#{{ session.session_id }}</strong><span v-if="session.created_by_actor_type==='api_client'" class="source-pill">外部 Skill<span v-if="session.skill_name"> · {{ session.skill_name }}</span></span><span v-else class="source-pill">网页生成</span></div><p v-if="session.title" class="session-title">{{ session.title }}</p><span class="session-count">{{ count(session) }}</span><small>入选计数</small><p>{{ new Date(session.generated_at).toLocaleString('zh-CN') }}</p><span :class="['session-status',session.status]">{{ session.status==='active'?'进行中':'已归档' }}</span><div class="card-actions" @click.stop.prevent><el-button size="small" @click="openEdit(session)">编辑</el-button><el-button size="small" :loading="removing===session.session_id" @click="removeSession(session)">删除</el-button></div></RouterLink></div></AsyncState></article>
  <el-dialog v-model="editOpen" title="编辑复习表" width="min(520px, calc(100vw - 24px))"><el-form label-position="top"><el-form-item label="标题"><el-input v-model="editForm.title" maxlength="200" placeholder="可选，便于区分"/></el-form-item><el-form-item label="备注"><el-input v-model="editForm.note" type="textarea" :rows="4" maxlength="5000"/></el-form-item></el-form><div v-if="editError" class="error-box" role="alert">{{ editError }}</div><template #footer><el-button @click="editOpen=false">取消</el-button><el-button type="primary" :loading="editSaving" @click="saveEdit">保存</el-button></template></el-dialog>
</section></template>
<style scoped>.generate-grid{display:grid;grid-template-columns:1.35fr .65fr;gap:18px}.strategy-title{display:flex;justify-content:space-between;gap:20px}.estimate{flex:0 0 auto;display:grid;text-align:right}.estimate strong{font:700 2rem Georgia,serif;color:var(--green-800)}.estimate span{font-size:.75rem;color:var(--muted)}.strategy-form>:last-child{width:100%;min-height:48px}.quota-grid{display:grid;gap:5px}.quota-field{display:grid;grid-template-columns:80px minmax(100px,1fr) 150px;align-items:center;gap:14px}.quota-field label,.selection-field label{font-weight:700}.selection-field{display:grid;gap:8px}.selection-field small{color:var(--muted)}.advanced-row{display:grid;grid-template-columns:1fr 1fr;gap:14px}.mobile-presets{display:none;gap:8px}.mobile-presets button{min-height:44px;padding:8px 12px;border:1px solid var(--line);border-radius:10px;background:#fff;color:var(--green-800)}.empty-notice{padding:14px;border-left:4px solid var(--amber);background:#fff8e6;border-radius:8px;color:#76540e}.steps{list-style:none;padding:0;margin:0;display:grid;gap:18px}.steps li{display:flex;gap:12px}.steps li>span{flex:0 0 34px;height:34px;display:grid;place-items:center;border-radius:50%;background:var(--green-100);color:var(--green-800);font-weight:800}.steps p{margin:4px 0;color:var(--muted)}.section-title{display:flex;justify-content:space-between;align-items:flex-start}.section-title h2 small{color:var(--muted)}.session-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.session-card{position:relative;display:grid;padding:16px;border:1px solid var(--line);border-radius:13px;color:var(--ink);text-decoration:none}.session-card:hover{border-color:var(--green-800);box-shadow:0 5px 18px rgba(18,55,42,.08)}.session-head{display:flex;justify-content:space-between;align-items:center;gap:8px}.session-title{font-weight:700;margin:6px 0 0;color:var(--ink);overflow-wrap:anywhere}.card-actions{display:flex;gap:8px;margin-top:12px}.session-count{font:700 2rem Georgia,serif;margin-top:14px}.session-card p,.session-card small{color:var(--muted);margin:2px 0}.session-status{position:absolute;right:14px;bottom:14px;font-size:.75rem}.session-status.archived{color:var(--muted)}.session-status.active{color:#3e8962}@media(max-width:1023px){.generate-grid{grid-template-columns:1fr}.session-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:639px){.strategy-title{align-items:flex-start}.quota-field{grid-template-columns:1fr 150px}.quota-field :deep(.el-slider){display:none}.mobile-presets{display:flex;overflow-x:auto}.advanced-row{grid-template-columns:1fr}.session-grid{grid-template-columns:1fr}}
</style>
