<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { useRouter } from 'vue-router'
import AsyncState from '@/components/AsyncState.vue'
import { generateSession, listSessions } from '@/api/practiceSessions'
import { normalizeApiError } from '@/api/client'
import { useAsyncState } from '@/composables/useAsyncState'
import type { PracticeSession, StrategyRequest } from '@/types/domain'

const router=useRouter();const state=useAsyncState<PracticeSession[]>([]);const total=ref(0);const generating=ref(false);const generateError=ref('')
const form=reactive<StrategyRequest>({new_words_limit:10,error_words_limit:15,due_words_limit:20,custom_words_limit:5,fallback_unreviewed_days:3})
async function load(){await state.run(async signal=>{const result=await listSessions(1,50,signal);total.value=Number(result.meta.total||0);return result.data}).catch(()=>{})}
async function generate(){generating.value=true;generateError.value='';try{const session=await generateSession({...form});ElMessage.success('复习表已生成');await router.push(`/daily/sessions/${session.session_id}`)}catch(e){const error=normalizeApiError(e);generateError.value=error.message+(error.requestId?`（请求编号 ${error.requestId}）`:'')}finally{generating.value=false}}
const count=(s:PracticeSession)=>Object.values(s.actual_counts).reduce((sum,value)=>sum+Number(value||0),0)
onMounted(load)
</script>
<template><section class="page"><div class="page-heading"><div><p class="eyebrow">PRACTICE SHEETS</p><p>按新词、错词、到期词和自定义词生成可复现的练习会话。</p></div></div>
  <div class="generate-grid"><form class="panel strategy-form" @submit.prevent="generate"><h2>生成一张复习表</h2><p class="muted">各类单词重叠时只会出现一次，数量不足属于正常情况。</p><div class="quota-grid"><el-form-item label="新词"><el-input-number v-model="form.new_words_limit" :min="0" :max="100"/></el-form-item><el-form-item label="错词"><el-input-number v-model="form.error_words_limit" :min="0" :max="100"/></el-form-item><el-form-item label="到期词"><el-input-number v-model="form.due_words_limit" :min="0" :max="100"/></el-form-item><el-form-item label="自定义词"><el-input-number v-model="form.custom_words_limit" :min="0" :max="100"/></el-form-item></div><el-form-item label="未复习兜底天数"><el-input-number v-model="form.fallback_unreviewed_days" :min="1" :max="365"/></el-form-item><div v-if="generateError" class="error-box" role="alert">{{ generateError }}</div><el-button native-type="submit" type="primary" size="large" :loading="generating">生成并打开</el-button></form>
    <article class="panel"><p class="eyebrow">HOW IT WORKS</p><h2>纸面为主，网页辅助</h2><ol class="steps"><li><span>1</span><div><strong>生成</strong><p>系统按记忆状态挑选单词并保存快照。</p></div></li><li><span>2</span><div><strong>线下复习</strong><p>阶段四将补齐正式的 A4 打印版式。</p></div></li><li><span>3</span><div><strong>结果回录</strong><p>每次新建轮次，逐个记录认识、不认识或跳过。</p></div></li></ol></article></div>
  <article class="panel"><div class="section-title"><div><p class="eyebrow">ALL SESSIONS</p><h2>历史复习表 <small>{{ total }}</small></h2></div><el-button :loading="state.loading.value" @click="load">刷新</el-button></div><AsyncState :phase="state.phase.value" :error="state.error.value" empty-text="还没有复习表。" @retry="load"><div class="session-grid"><RouterLink v-for="session in state.data.value" :key="session.session_id" class="session-card" :to="`/daily/sessions/${session.session_id}`"><div class="session-head"><strong>#{{ session.session_id }}</strong><span v-if="session.created_by_actor_type==='api_client'" class="source-pill">外部 Skill<span v-if="session.skill_name"> · {{ session.skill_name }}</span></span><span v-else class="source-pill">网页生成</span></div><span class="session-count">{{ count(session) }}</span><small>入选计数</small><p>{{ new Date(session.generated_at).toLocaleString('zh-CN') }}</p><span :class="['session-status',session.status]">{{ session.status==='active'?'进行中':'已归档' }}</span></RouterLink></div></AsyncState></article>
</section></template>
<style scoped>.generate-grid{display:grid;grid-template-columns:1.25fr .75fr;gap:18px}.strategy-form>:last-child{width:100%;min-height:48px}.quota-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:0 14px}.steps{list-style:none;padding:0;margin:0;display:grid;gap:18px}.steps li{display:flex;gap:12px}.steps li>span{flex:0 0 34px;height:34px;display:grid;place-items:center;border-radius:50%;background:var(--green-100);color:var(--green-800);font-weight:800}.steps p{margin:4px 0;color:var(--muted)}.section-title{display:flex;justify-content:space-between;align-items:flex-start}.section-title h2 small{color:var(--muted)}.session-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.session-card{position:relative;display:grid;padding:16px;border:1px solid var(--line);border-radius:13px;color:var(--ink);text-decoration:none}.session-card:hover{border-color:var(--green-800);box-shadow:0 5px 18px rgba(18,55,42,.08)}.session-head{display:flex;justify-content:space-between;align-items:center;gap:8px}.session-count{font:700 2rem Georgia,serif;margin-top:14px}.session-card p,.session-card small{color:var(--muted);margin:2px 0}.session-status{position:absolute;right:14px;bottom:14px;font-size:.75rem}.session-status.archived{color:var(--muted)}.session-status.active{color:#3e8962}@media(max-width:1023px){.session-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:639px){.generate-grid{grid-template-columns:1fr}.quota-grid{grid-template-columns:1fr 1fr}.session-grid{grid-template-columns:1fr}}</style>
