<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import AsyncState from '@/components/AsyncState.vue';import ResultSelector from '@/components/ResultSelector.vue'
import { correctReview, listReviews } from '@/api/reviews';import { getWord } from '@/api/words';import { normalizeApiError } from '@/api/client';import { useAsyncState } from '@/composables/useAsyncState'
import type { ReviewFilters, ReviewLog, ReviewStatus, Word } from '@/types/domain'

const route=useRoute(),router=useRouter();const state=useAsyncState<ReviewLog[]>([]);const total=ref(0);const words=ref(new Map<number,Word>());const editingId=ref<number|null>(null);const busyId=ref<number|null>(null);const rowError=ref(new Map<number,string>());const filterOpen=ref(false)
const filters=reactive<ReviewFilters>({page:Number(route.query.page)||1,size:20,word_id:route.query.word_id?Number(route.query.word_id):undefined,status:(route.query.status as ReviewStatus)||undefined,source:(route.query.source as ReviewFilters['source'])||undefined,actor_type:(route.query.actor_type as ReviewFilters['actor_type'])||undefined,session_id:route.query.session_id?Number(route.query.session_id):undefined,round_id:route.query.round_id?Number(route.query.round_id):undefined,reviewed_from:String(route.query.reviewed_from||'')||undefined,reviewed_to:String(route.query.reviewed_to||'')||undefined,sort:'reviewed_at_desc'})
let timer:number|undefined
async function load(){await state.run(async signal=>{const result=await listReviews(filters,signal);total.value=Number(result.meta.total||0);const missing=[...new Set(result.data.map(r=>r.word_id))].filter(id=>!words.value.has(id));const fetched=await Promise.all(missing.map(id=>getWord(id,signal).catch(()=>null)));const next=new Map(words.value);fetched.forEach(word=>{if(word)next.set(word.id,word)});words.value=next;return result.data}).catch(()=>{})}
watch(filters,()=>{window.clearTimeout(timer);timer=window.setTimeout(()=>{router.replace({query:{...(filters.word_id?{word_id:String(filters.word_id)}:{}),...(filters.status?{status:filters.status}:{}),...(filters.source?{source:filters.source}:{}),...(filters.actor_type?{actor_type:filters.actor_type}:{}),...(filters.session_id?{session_id:String(filters.session_id)}:{}),...(filters.round_id?{round_id:String(filters.round_id)}:{}),...(filters.reviewed_from?{reviewed_from:filters.reviewed_from}:{}),...(filters.reviewed_to?{reviewed_to:filters.reviewed_to}:{}),...(filters.page!==1?{page:String(filters.page)}:{})}});load()},200)},{deep:true});onMounted(load)
async function save(review:ReviewLog,status:ReviewStatus){busyId.value=review.id;const errors=new Map(rowError.value);errors.delete(review.id);rowError.value=errors;try{const updated=await correctReview(review,status);const rows=[...(state.data.value||[])];const index=rows.findIndex(item=>item.id===review.id);if(index>=0)rows[index]=updated;state.data.value=rows;editingId.value=null}catch(e){const error=normalizeApiError(e);rowError.value=new Map(rowError.value).set(review.id,error.isConflict?'记录已在其他页面修改，请刷新后重试。':error.message)}finally{busyId.value=null}}
const pageCount=computed(()=>Math.max(1,Math.ceil(total.value/(filters.size||20))));const statusText=(s:ReviewStatus)=>({known:'认识',unknown:'不认识',skipped:'跳过'}[s]);const sourceText=(s:string)=>({quick_review:'快速复习',online_practice:'在线卡片',print_manual:'线下回录'}[s]||s)
</script>
<template><section class="page"><div class="page-heading"><div><p class="eyebrow">REVIEW HISTORY</p><p>共 {{ total }} 条复习记录，每次修改都会同步重算统计。</p></div><el-button class="mobile-filter" @click="filterOpen=true">筛选</el-button></div><div class="panel filters desktop-filters"><el-input v-model.number="filters.word_id" clearable type="number" placeholder="单词 ID" aria-label="单词 ID"/><el-select v-model="filters.status" clearable placeholder="全部结果" aria-label="复习结果"><el-option label="认识" value="known"/><el-option label="不认识" value="unknown"/><el-option label="跳过" value="skipped"/></el-select><el-select v-model="filters.source" clearable placeholder="全部来源" aria-label="复习来源"><el-option label="快速复习" value="quick_review"/><el-option label="在线卡片" value="online_practice"/><el-option label="线下回录" value="print_manual"/></el-select><el-select v-model="filters.actor_type" clearable placeholder="全部操作者" aria-label="操作者类型"><el-option label="网页用户" value="web_user"/><el-option label="外部 Skill" value="api_client"/></el-select><el-input v-model.number="filters.session_id" clearable type="number" placeholder="复习表 ID" aria-label="复习表 ID"/><el-input v-model.number="filters.round_id" clearable type="number" placeholder="轮次 ID" aria-label="轮次 ID"/><input v-model="filters.reviewed_from" class="filter-input" type="date" aria-label="复习开始日期"/><input v-model="filters.reviewed_to" class="filter-input" type="date" aria-label="复习结束日期"/></div>
  <div class="panel history-panel"><AsyncState :phase="state.phase.value" :error="state.error.value" empty-text="还没有复习记录。" @retry="load"><div class="desktop-history local-scroll"><el-table :data="state.data.value" row-key="id" style="min-width:760px"><el-table-column label="时间" width="175"><template #default="{row}">{{ new Date(row.reviewed_at).toLocaleString('zh-CN') }}</template></el-table-column><el-table-column label="单词" min-width="150"><template #default="{row}"><strong>{{ words.get(row.word_id)?.en_word||`单词 #${row.word_id}` }}</strong><small>{{ words.get(row.word_id)?.cn_meaning }}</small></template></el-table-column><el-table-column label="来源" width="110"><template #default="{row}">{{ sourceText(row.source) }}</template></el-table-column><el-table-column label="结果" min-width="300"><template #default="{row}"><ResultSelector v-if="editingId===row.id" compact :model-value="row.status" :disabled="busyId===row.id" @select="status=>save(row,status)"/><button v-else type="button" :class="['status-badge',row.status]" @click="editingId=row.id">{{ statusText(row.status) }} · 修改</button><p v-if="rowError.get(row.id)" class="row-error" role="alert">{{ rowError.get(row.id) }}</p></template></el-table-column></el-table></div>
    <div class="mobile-history"><article v-for="review in state.data.value" :key="review.id" class="history-card"><time>{{ new Date(review.reviewed_at).toLocaleString('zh-CN') }}</time><h2>{{ words.get(review.word_id)?.en_word||`单词 #${review.word_id}` }}</h2><p>{{ words.get(review.word_id)?.cn_meaning }}</p><span class="source-pill">{{ sourceText(review.source) }}</span><ResultSelector v-if="editingId===review.id" compact :model-value="review.status" :disabled="busyId===review.id" @select="status=>save(review,status)"/><button v-else type="button" :class="['status-badge',review.status]" @click="editingId=review.id">{{ statusText(review.status) }} · 点按修改</button><p v-if="rowError.get(review.id)" class="row-error" role="alert">{{ rowError.get(review.id) }}</p></article></div><div v-if="pageCount>1" class="pagination"><el-pagination v-model:current-page="filters.page" layout="prev, pager, next" :page-count="pageCount"/></div></AsyncState></div>
  <el-drawer v-model="filterOpen" title="筛选历史" size="90%"><div class="drawer-filters"><el-input v-model.number="filters.word_id" clearable type="number" placeholder="单词 ID"/><el-select v-model="filters.status" clearable placeholder="全部结果"><el-option label="认识" value="known"/><el-option label="不认识" value="unknown"/><el-option label="跳过" value="skipped"/></el-select><el-select v-model="filters.source" clearable placeholder="全部来源"><el-option label="快速复习" value="quick_review"/><el-option label="在线卡片" value="online_practice"/><el-option label="线下回录" value="print_manual"/></el-select><el-select v-model="filters.actor_type" clearable placeholder="全部操作者"><el-option label="网页用户" value="web_user"/><el-option label="外部 Skill" value="api_client"/></el-select><el-input v-model.number="filters.session_id" clearable type="number" placeholder="复习表 ID"/><el-input v-model.number="filters.round_id" clearable type="number" placeholder="轮次 ID"/><label>复习开始日期<input v-model="filters.reviewed_from" class="filter-input" type="date"/></label><label>复习结束日期<input v-model="filters.reviewed_to" class="filter-input" type="date"/></label><el-button type="primary" @click="filterOpen=false">查看结果</el-button></div></el-drawer>
</section></template>
<style scoped>.filters{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:12px}.filter-input{width:100%;min-height:40px;padding:0 11px;border:1px solid #dcdfe6;border-radius:4px;background:#fff;color:var(--ink)}.mobile-filter,.mobile-history{display:none}.desktop-history strong,.desktop-history small{display:block}.desktop-history small{margin-top:3px;color:var(--muted)}.status-badge{min-height:44px;padding:6px 13px;border-radius:999px;border:1px solid var(--line);background:#fff;cursor:pointer}.status-badge.known{color:#307251;background:#e8f5ed}.status-badge.unknown{color:#a53c38;background:#fff0ef}.status-badge.skipped{color:#80601f;background:#fff7df}.row-error{color:var(--red);font-size:.78rem}.drawer-filters{display:grid;gap:14px}.drawer-filters label{display:grid;gap:6px;color:var(--muted);font-size:.85rem}@media(max-width:639px){.desktop-filters,.desktop-history{display:none}.mobile-filter{display:inline-flex}.history-panel{padding:0;background:transparent;border:0;box-shadow:none}.mobile-history{display:grid;gap:12px}.history-card{display:grid;gap:8px;padding:15px;background:var(--paper);border:1px solid var(--line);border-radius:13px}.history-card time{font-size:.75rem;color:var(--muted)}.history-card h2{font:700 1.35rem Georgia,serif;margin:0}.history-card p{margin:0;color:var(--muted)}.history-card .source-pill{justify-self:start}}</style>
