<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage } from 'element-plus'
import AsyncState from '@/components/AsyncState.vue';import ResultSelector from '@/components/ResultSelector.vue'
import { createRound, getSession, putRoundResult } from '@/api/practiceSessions';import { newEventId, normalizeApiError } from '@/api/client';import { useAsyncState } from '@/composables/useAsyncState'
import type { PracticeRound, PracticeSession, ReviewLog, ReviewStatus } from '@/types/domain'

const route=useRoute();const id=Number(route.params.id);const state=useAsyncState<PracticeSession>();const round=ref<PracticeRound|null>(null);const results=ref(new Map<number,ReviewLog>());const eventIds=new Map<number,string>();const busyItem=ref<number|null>(null);const error=ref('');const starting=ref(false)
async function load(){await state.run(signal=>getSession(id,signal)).catch(()=>{})}
async function startRound(){starting.value=true;error.value='';try{round.value=await createRound(id,'offline');results.value=new Map();ElMessage.success('已开始一轮新的线下结果回录')}catch(e){error.value=normalizeApiError(e).message}finally{starting.value=false}}
async function select(itemId:number,status:ReviewStatus){if(!round.value)return;busyItem.value=itemId;error.value='';const existing=results.value.get(itemId);const eventId=existing?.client_event_id||eventIds.get(itemId)||newEventId();eventIds.set(itemId,eventId);try{const saved=await putRoundResult(round.value.round_id,itemId,status,eventId,existing?.version);results.value=new Map(results.value).set(itemId,saved)}catch(e){const normalized=normalizeApiError(e);error.value=normalized.isConflict?'结果已在其他页面修改，请刷新后继续。':normalized.message}finally{busyItem.value=null}}
const answered=computed(()=>results.value.size);const sourceLabel=(source:string)=>({new:'新词',error:'错词',due:'到期',custom:'自定义'}[source]||source)
onMounted(load)
</script>
<template><section class="page"><AsyncState :phase="state.phase.value" :error="state.error.value" @retry="load"><template v-if="state.data.value"><div class="page-heading"><div><p class="eyebrow">SESSION #{{ state.data.value.session_id }}</p><p>{{ new Date(state.data.value.generated_at).toLocaleString('zh-CN') }} · 种子 {{ state.data.value.seed }}</p></div><div class="button-row"><span v-if="state.data.value.created_by_actor_type==='api_client'" class="source-pill">外部 Skill · {{ state.data.value.skill_name||'未命名客户端' }}</span><el-button :loading="starting" type="primary" @click="startRound">{{ round?'开始新一轮':'开始结果回录' }}</el-button></div></div>
  <div v-if="round" class="round-banner" aria-live="polite"><div><strong>线下回录轮次 #{{ round.round_id }}</strong><span>已保存 {{ answered }} / {{ state.data.value.items?.length||0 }}</span></div><el-progress :percentage="Math.round(answered/(state.data.value.items?.length||1)*100)"/></div><div v-else class="panel intro-banner"><strong>完成纸面复习后，点击“开始结果回录”创建本次流水。</strong><p>每次实际复习都应开始新一轮；如果只是纠正本轮误录，直接改选即可。</p></div>
  <div v-if="error" class="error-box" role="alert">未保存：{{ error }}</div>
  <div class="record-list"><article v-for="item in state.data.value.items" :key="item.item_id" class="record-card panel"><div class="record-position">{{ item.position }}</div><div class="record-word"><div class="tag-list"><span v-for="source in item.source_categories" :key="source" class="source-pill">{{ sourceLabel(source) }}</span></div><h2>{{ item.word.en_word }}</h2><p v-if="item.word.phonetic" class="phonetic">{{ item.word.phonetic }}</p><strong>{{ item.word.cn_meaning }}</strong><p v-if="item.word.example_sentence" class="example">{{ item.word.example_sentence }}</p></div><div class="record-result"><ResultSelector compact :model-value="results.get(item.item_id)?.status||null" :disabled="!round||busyItem===item.item_id" @select="status=>select(item.item_id,status)"/><small>{{ results.has(item.item_id)?'已保存，可改选':'尚未记录' }}</small></div></article></div>
  </template></AsyncState></section></template>
<style scoped>.round-banner{position:sticky;top:10px;z-index:8;display:grid;grid-template-columns:1fr minmax(180px,340px);align-items:center;gap:20px;padding:14px 18px;background:var(--green-950);color:#fff;border-radius:14px;box-shadow:var(--shadow)}.round-banner>div{display:grid;gap:3px}.round-banner span{color:#bfd1c8;font-size:.82rem}.intro-banner p{margin:6px 0 0;color:var(--muted)}.record-list{display:grid;gap:12px}.record-card{display:grid;grid-template-columns:42px minmax(240px,1fr) minmax(300px,.85fr);gap:18px;align-items:center}.record-position{width:36px;height:36px;display:grid;place-items:center;border-radius:50%;background:var(--green-100);color:var(--green-800);font-weight:800}.record-word h2{font:700 1.5rem Georgia,serif;margin:8px 0 2px}.record-word p{margin:2px 0;color:var(--muted)}.record-word .phonetic{color:var(--green-800)}.record-word .example{font-style:italic;margin-top:8px}.record-result{display:grid;gap:6px}.record-result small{text-align:center;color:var(--muted)}@media(max-width:767px){.round-banner{grid-template-columns:1fr}.record-card{grid-template-columns:36px 1fr}.record-result{grid-column:1/-1}.record-position{width:32px;height:32px}}@media(max-width:639px){.round-banner{top:0;border-radius:10px}.record-card{padding:14px}}</style>
