<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useRoute, useRouter } from 'vue-router'
import AsyncState from '@/components/AsyncState.vue'; import ResponsiveWordList from '@/components/ResponsiveWordList.vue'; import WordEditorDialog from '@/components/WordEditorDialog.vue'
import { ApiError, normalizeApiError } from '@/api/client'; import { createWord, deleteWord, exportWords, importWords, listWords, updateWord } from '@/api/words'
import { useAsyncState } from '@/composables/useAsyncState'; import type { ImportSummary, Word, WordFilters, WordPayload } from '@/types/domain'

const route=useRoute(),router=useRouter();const state=useAsyncState<Word[]>([]);const total=ref(0);const editorOpen=ref(false);const editing=ref<Word|null>(null);const submitting=ref(false);const writeError=ref('');const importOpen=ref(false);const importFile=ref<File|null>(null);const importText=ref('');const importPolicy=ref<'skip'|'update'|'reject'>('reject');const importUnresolvedPolicy=ref<'skip'|'reject'|'ai'>('ai');const importDryRun=ref(false);const importResult=ref<ImportSummary|null>(null);const importError=ref<ApiError|null>(null);const importing=ref(false);const filterOpen=ref(false)
const filters=reactive<WordFilters>({page:Number(route.query.page)||1,size:20,keyword:String(route.query.keyword||''),tag:String(route.query.tag||'').split(',').map(value=>value.trim()).filter(Boolean),is_custom:route.query.is_custom==='true'?true:route.query.is_custom==='false'?false:undefined,created_from:String(route.query.created_from||'')||undefined,created_to:String(route.query.created_to||'')||undefined,sort:(route.query.sort as WordFilters['sort'])||'created_at_desc'})
let timer:number|undefined
async function load(){await state.run(async signal=>{const result=await listWords(filters,signal);total.value=Number(result.meta.total||0);return result.data}).catch(()=>{})}
function sync(){router.replace({query:{...(filters.keyword?{keyword:filters.keyword}:{}),...(filters.tag?.length?{tag:filters.tag.join(',')}:{}),...(filters.is_custom!==undefined?{is_custom:String(filters.is_custom)}:{}),...(filters.created_from?{created_from:filters.created_from}:{}),...(filters.created_to?{created_to:filters.created_to}:{}),...(filters.sort!=='created_at_desc'?{sort:filters.sort}:{}),...(filters.page!==1?{page:String(filters.page)}:{})}})}
function setTags(value:string){filters.tag=value.split(/[,，]/).map(item=>item.trim()).filter(Boolean);filters.page=1}
watch(filters,()=>{window.clearTimeout(timer);timer=window.setTimeout(()=>{sync();load()},250)},{deep:true});onMounted(load)
function openCreate(){editing.value=null;writeError.value='';editorOpen.value=true}function openEdit(word:Word){editing.value=word;writeError.value='';editorOpen.value=true}
async function save(payload:WordPayload){submitting.value=true;writeError.value='';try{if(editing.value)await updateWord(editing.value.id,{...payload,expected_version:editing.value.version});else await createWord(payload);editorOpen.value=false;ElMessage.success('已保存');await load()}catch(e){const error=normalizeApiError(e);writeError.value=error.isConflict?'单词已存在或已被其他操作修改。请关闭后刷新再试。':error.message+(error.requestId?`（请求编号 ${error.requestId}）`:'')}finally{submitting.value=false}}
async function remove(word:Word){try{await ElMessageBox.confirm(`“${word.en_word}”将被软删除，历史记录仍会保留。`,'确认删除',{confirmButtonText:'删除',cancelButtonText:'取消',type:'warning'});await deleteWord(word);ElMessage.success('已删除');await load()}catch(e){if(e==='cancel'||e==='close')return;const error=normalizeApiError(e);ElMessage.error(error.isConflict?'数据已变化，请刷新后重试':error.message);await load()}}
function onFile(event:Event){const files=(event.target as HTMLInputElement).files;importFile.value=files?.[0]||null;importResult.value=null;importError.value=null}
async function runImport(){const file=importFile.value||new File([importText.value.trim()], 'words.txt', {type:'text/plain'});if(!file.size){importError.value=new ApiError('请选择文件或输入英文单词');return}const ext=file.name.split('.').pop()?.toLowerCase();const mimeByExt:Record<string,string[]>={txt:['','text/plain'],csv:['','text/csv','application/csv','application/vnd.ms-excel'],json:['','application/json','text/json']};if(!ext||!mimeByExt[ext]){importError.value=new ApiError('请选择 TXT、CSV 或 JSON 文件');return}if(!mimeByExt[ext].includes(file.type)){importError.value=new ApiError(`文件类型 ${file.type||'未知'} 与 .${ext} 扩展名不匹配`);return}if(file.size>10*1024*1024){importError.value=new ApiError('文件不能超过 10 MB');return}importing.value=true;importError.value=null;try{importResult.value=await importWords(file,importPolicy.value,importDryRun.value,importUnresolvedPolicy.value);if(!importDryRun.value)await load()}catch(e){importError.value=normalizeApiError(e)}finally{importing.value=false}}
const pageCount=computed(()=>Math.max(1,Math.ceil(total.value/(filters.size||20))))
</script>
<template><section class="page"><div class="page-heading"><div><p class="eyebrow">VOCABULARY</p><p>共 {{ total }} 个单词，筛选条件会保存在地址栏。</p></div><div class="button-row"><el-button class="mobile-filter" @click="filterOpen=true">筛选</el-button><el-button @click="importOpen=true">导入 / 导出</el-button><el-button type="primary" @click="openCreate">新增单词</el-button></div></div>
  <div class="panel filters desktop-filters"><el-input v-model="filters.keyword" clearable placeholder="搜索英文或中文" aria-label="搜索英文或中文"/><el-input :model-value="filters.tag?.join(', ')" clearable placeholder="标签，逗号分隔" aria-label="标签筛选" @update:model-value="setTags"/><el-select v-model="filters.is_custom" clearable placeholder="全部类型" aria-label="自定义词筛选"><el-option label="自定义词" :value="true"/><el-option label="普通词" :value="false"/></el-select><input v-model="filters.created_from" class="filter-input" type="date" aria-label="创建开始日期"/><input v-model="filters.created_to" class="filter-input" type="date" aria-label="创建结束日期"/><el-select v-model="filters.sort" aria-label="排序"><el-option label="最新创建" value="created_at_desc"/><el-option label="最早创建" value="created_at_asc"/><el-option label="英文 A–Z" value="en_word_asc"/><el-option label="英文 Z–A" value="en_word_desc"/></el-select></div>
  <div class="panel"><AsyncState :phase="state.phase.value" :error="state.error.value" empty-text="词库还是空的，先加入第一个单词吧。" @retry="load"><template #empty-action><el-button type="primary" @click="openCreate">新增单词</el-button></template><ResponsiveWordList v-if="state.data.value" :words="state.data.value" @edit="openEdit" @remove="remove" @review="word=>$router.push({path:'/history',query:{word_id:word.id}})"/><div v-if="pageCount>1" class="pagination"><el-pagination v-model:current-page="filters.page" layout="prev, pager, next" :page-count="pageCount"/></div></AsyncState></div>
  <WordEditorDialog v-model="editorOpen" :word="editing" :submitting="submitting" :error="writeError" @submit="save"/>
  <el-drawer v-model="filterOpen" title="筛选单词" size="90%"><div class="drawer-filters"><el-input v-model="filters.keyword" clearable placeholder="搜索英文或中文"/><el-input :model-value="filters.tag?.join(', ')" clearable placeholder="标签，逗号分隔" @update:model-value="setTags"/><el-select v-model="filters.is_custom" clearable placeholder="全部类型"><el-option label="自定义词" :value="true"/><el-option label="普通词" :value="false"/></el-select><label>创建开始日期<input v-model="filters.created_from" class="filter-input" type="date"/></label><label>创建结束日期<input v-model="filters.created_to" class="filter-input" type="date"/></label><el-select v-model="filters.sort"><el-option label="最新创建" value="created_at_desc"/><el-option label="最早创建" value="created_at_asc"/><el-option label="英文 A–Z" value="en_word_asc"/><el-option label="英文 Z–A" value="en_word_desc"/></el-select><el-button type="primary" @click="filterOpen=false">查看结果</el-button></div></el-drawer>
  <el-dialog v-model="importOpen" title="导入与导出" width="min(620px, calc(100vw - 24px))"><h3>只输入英文，自动生成词条</h3><p class="muted">每行一个英文单词，或选择 .txt 文件；也兼容完整字段的 CSV / JSON。</p><el-input v-model="importText" type="textarea" :rows="6" placeholder="abandon&#10;camera&#10;focus" aria-label="英文单词列表"/><div class="import-or">或者选择文件</div><input class="file-input" type="file" accept=".txt,.csv,.json,text/plain,text/csv,application/json" @change="onFile"/><el-radio-group v-model="importPolicy"><el-radio-button value="reject">冲突即拒绝</el-radio-button><el-radio-button value="skip">跳过重复</el-radio-button><el-radio-button value="update">更新重复</el-radio-button></el-radio-group><p class="muted import-label">词典未命中的单词（查不到且未填中文释义）：</p><el-radio-group v-model="importUnresolvedPolicy"><el-radio-button value="skip">跳过未命中</el-radio-button><el-radio-button value="ai">AI 补充</el-radio-button><el-radio-button value="reject">未命中即拒绝</el-radio-button></el-radio-group><el-checkbox v-model="importDryRun">仅校验，不写入</el-checkbox><div v-if="importError" class="error-box" role="alert"><strong>本次零写入。</strong> {{ importError.message }}<span v-if="importError.requestId" class="request-id">请求编号：{{ importError.requestId }}</span></div><dl v-if="importResult" class="import-summary"><div><dt>新增</dt><dd>{{ importResult.created }}</dd></div><div><dt>更新</dt><dd>{{ importResult.updated }}</dd></div><div><dt>跳过</dt><dd>{{ importResult.skipped }}</dd></div><div><dt>未命中</dt><dd>{{ importResult.unresolved||0 }}</dd></div><div><dt>词典命中</dt><dd>{{ importResult.dictionary_matches||0 }}</dd></div><div><dt>总计</dt><dd>{{ importResult.total }}</dd></div></dl><div v-if="importResult?.unresolved_words?.length" class="unresolved-box" role="status"><strong>以下 {{ importResult.unresolved_words.length }} 个单词未命中词典，未导入：</strong><span class="unresolved-words">{{ importResult.unresolved_words.join('、') }}</span><p class="muted">可改用 CSV / JSON 并为它们补上 cn_meaning 后重新导入。</p></div><el-button type="primary" :loading="importing" :disabled="!importFile&&!importText.trim()" @click="runImport">{{ importDryRun?'开始校验':'开始导入' }}</el-button><el-divider/><h3>导出当前筛选范围</h3><div class="button-row"><el-button @click="exportWords('csv',filters)">导出 CSV</el-button><el-button @click="exportWords('json',filters)">导出 JSON</el-button></div></el-dialog>
</section></template>
<style scoped>.filters{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px}.mobile-filter{display:none}.drawer-filters{display:grid;gap:14px}.drawer-filters label{display:grid;gap:6px;color:var(--muted);font-size:.85rem}.filter-input{width:100%;min-height:40px;padding:0 11px;border:1px solid #dcdfe6;border-radius:4px;background:#fff;color:var(--ink)}.file-input{display:block;width:100%;min-height:48px;margin:10px 0}.import-or{text-align:center;color:var(--muted);font-size:.8rem;margin-top:10px}.import-label{font-size:.78rem;margin:10px 0 4px}.unresolved-box{margin-top:10px;padding:10px 12px;background:var(--yellow-100,#fff7e6);border:1px solid var(--yellow-300,#ffd591);border-radius:8px;font-size:.85rem}.unresolved-box .unresolved-words{display:block;margin:6px 0 4px;color:var(--ink);word-break:break-all}.import-summary{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.import-summary div{padding:10px;text-align:center;background:var(--green-100);border-radius:8px}.import-summary dt{font-size:.75rem;color:var(--muted)}.import-summary dd{margin:4px 0 0;font-weight:800}@media(max-width:639px){.desktop-filters{display:none}.mobile-filter{display:inline-flex}.import-summary{grid-template-columns:repeat(3,1fr)}}</style>
