<script setup lang="ts">
import { computed, onMounted, onUnmounted, reactive, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useRoute, useRouter } from 'vue-router'
import AsyncState from '@/components/AsyncState.vue'; import ResponsiveWordList from '@/components/ResponsiveWordList.vue'; import WordEditorDialog from '@/components/WordEditorDialog.vue'
import { ApiError, normalizeApiError } from '@/api/client'; import { batchDeleteWords, batchGenerateAudio, batchResetProgress, batchSetTags, createWord, deleteWord, exportWords, generateMissingWordAudio, generateNumberAudio, generateWordAudio, listAudioProgress, listImportProgress, listWords, regenerateAllAudio, resetWordProgress, startImport, updateWord, wordAudioUrl } from '@/api/words'
import { useAsyncState } from '@/composables/useAsyncState'; import type { AudioProgress, BatchItem, ImportProgress, ImportSummary, Word, WordFilters, WordPayload } from '@/types/domain'
import { createInlineImportFile } from '@/views/importFile'

const route=useRoute(),router=useRouter();const state=useAsyncState<Word[]>([]);const total=ref(0);const editorOpen=ref(false);const editing=ref<Word|null>(null);const submitting=ref(false);const writeError=ref('');const importOpen=ref(false);const importFile=ref<File|null>(null);const importText=ref('');const importPolicy=ref<'skip'|'update'|'reject'>('update');const importUnresolvedPolicy=ref<'skip'|'reject'|'ai'>('ai');const importDryRun=ref(false);const importTags=ref('');const importResult=ref<ImportSummary|null>(null);const importError=ref<ApiError|null>(null);const importing=ref(false);const importProgress=ref<ImportProgress|null>(null);let importPollTimer:number|undefined;const filterOpen=ref(false);const jsonTemplateOpen=ref(false);const batchAudioLoading=ref(false);const regeneratingAll=ref(false);const generatingNumbers=ref(false);const audioProgress=ref<AudioProgress|null>(null)
const selectedWords=ref<Word[]>([]);const wordListRef=ref<{clearSelection:()=>void}|null>(null);const batchTagOpen=ref(false);const batchTagInput=ref('');const batchBusy=ref(false);const batchAudioBusy=ref(false)
let playingAudio:HTMLAudioElement|null=null;let progressTimer:number|undefined
const jsonTemplate=JSON.stringify([{en_word:'example',phonetic:'ɪɡˈzæmpəl',cn_meaning:'例子；示例',example_sentence:'This is an example.',is_custom:false,tags:['基础','示例']}],null,2)
const filters=reactive<WordFilters>({page:Number(route.query.page)||1,size:20,keyword:String(route.query.keyword||''),tag:String(route.query.tag||'').split(',').map(value=>value.trim()).filter(Boolean),is_custom:route.query.is_custom==='true'?true:route.query.is_custom==='false'?false:undefined,created_from:String(route.query.created_from||'')||undefined,created_to:String(route.query.created_to||'')||undefined,sort:(route.query.sort as WordFilters['sort'])||'created_at_desc'})
let timer:number|undefined
async function load(){await state.run(async signal=>{const result=await listWords(filters,signal);total.value=Number(result.meta.total||0);return result.data}).catch(()=>{})}
function sync(){router.replace({query:{...(filters.keyword?{keyword:filters.keyword}:{}),...(filters.tag?.length?{tag:filters.tag.join(',')}:{}),...(filters.is_custom!==undefined?{is_custom:String(filters.is_custom)}:{}),...(filters.created_from?{created_from:filters.created_from}:{}),...(filters.created_to?{created_to:filters.created_to}:{}),...(filters.sort!=='created_at_desc'?{sort:filters.sort}:{}),...(filters.page!==1?{page:String(filters.page)}:{})}})}
function setTags(value:string){filters.tag=value.split(/[,，]/).map(item=>item.trim()).filter(Boolean);filters.page=1}
watch(filters,()=>{window.clearTimeout(timer);timer=window.setTimeout(()=>{sync();load()},250)},{deep:true});onMounted(()=>{load()});onUnmounted(()=>{playingAudio?.pause();playingAudio=null;stopProgressPolling();stopImportPolling()})
function openCreate(){editing.value=null;writeError.value='';editorOpen.value=true}function openEdit(word:Word){editing.value=word;writeError.value='';editorOpen.value=true}
async function save(payload:WordPayload){submitting.value=true;writeError.value='';try{if(editing.value)await updateWord(editing.value.id,{...payload,expected_version:editing.value.version});else await createWord(payload);editorOpen.value=false;ElMessage.success('已保存');await load()}catch(e){const error=normalizeApiError(e);writeError.value=error.isConflict?'单词已存在或已被其他操作修改。请关闭后刷新再试。':error.message+(error.requestId?`（请求编号 ${error.requestId}）`:'')}finally{submitting.value=false}}
async function remove(word:Word){try{await ElMessageBox.confirm(`“${word.en_word}”将被软删除，历史记录仍会保留。`,'确认删除',{confirmButtonText:'删除',cancelButtonText:'取消',type:'warning'});await deleteWord(word);ElMessage.success('已删除');await load()}catch(e){if(e==='cancel'||e==='close')return;const error=normalizeApiError(e);ElMessage.error(error.isConflict?'数据已变化，请刷新后重试':error.message);await load()}}
async function resetProgress(word:Word){try{await ElMessageBox.confirm(`将清空“${word.en_word}”的全部复习记录，让它重新作为新词出现（间隔从 1 天重新开始）。单词本身不会被删除。`,'确认设为新词',{confirmButtonText:'清空并设为新词',cancelButtonText:'取消',type:'warning'});await resetWordProgress(word.id);ElMessage.success('已设为新词，复习记录已清空');await load()}catch(e){if(e==='cancel'||e==='close')return;const error=normalizeApiError(e);ElMessage.error(error.isConflict?'数据已变化，请刷新后重试':error.message);await load()}}
async function playAudio(word:Word){try{playingAudio?.pause();playingAudio=new Audio(wordAudioUrl(word.id));await playingAudio.play()}catch(e){const error=normalizeApiError(e);ElMessage.error(error.status===404?'音频尚未生成，请先生成音频':error.message)}}
async function generateAudio(word:Word){try{await generateWordAudio(word.id,Boolean(word.audio_path));ElMessage.success(word.audio_path?'已重新生成音频':'已生成音频');await load()}catch(e){const error=normalizeApiError(e);ElMessage.error(error.message)}}
async function generateMissingAudio(){batchAudioLoading.value=true;try{const result=await generateMissingWordAudio(50);ElMessage.success(`已加入后台队列 ${result.queued} 个`);startProgressPolling()}catch(e){const error=normalizeApiError(e);ElMessage.error(error.message)}finally{batchAudioLoading.value=false}}
async function regenerateAll(){try{await ElMessageBox.confirm('将用当前配置的自定义语音 API 对全部单词强制重新生成音频(覆盖旧文件),会在后台进行,可能消耗较多额度。','确认全部重新生成',{confirmButtonText:'全部重新生成',cancelButtonText:'取消',type:'warning'})}catch{return};regeneratingAll.value=true;try{const result=await regenerateAllAudio();ElMessage.success(`已加入后台队列 ${result.queued} 个`);startProgressPolling()}catch(e){const error=normalizeApiError(e);ElMessage.error(error.message)}finally{regeneratingAll.value=false}}
async function generateNumbersAudio(){generatingNumbers.value=true;try{const result=await generateNumberAudio(false);ElMessage.success(result.queued>0?`已加入后台队列生成 ${result.queued} 段序号音频`:'序号音频(1–50)已全部生成,无需重做');if(result.queued>0)startProgressPolling()}catch(e){const error=normalizeApiError(e);ElMessage.error(error.message)}finally{generatingNumbers.value=false}}
const audioProgressPercent=()=>{const p=audioProgress.value;if(!p||!p.total)return 0;return Math.round(((p.completed+p.failed)/p.total)*100)}
function stopProgressPolling(){if(progressTimer!==undefined){window.clearInterval(progressTimer);progressTimer=undefined}}
async function tickProgress(){try{const p=await listAudioProgress();audioProgress.value=p;if(p.state==='idle'&&p.total>0){stopProgressPolling();const failed=p.failed?`，失败 ${p.failed}`:'';ElMessage.success(`后台生成完成:共 ${p.total} 个${failed}`);await load()}}catch{/* 静默,下次 tick 再试 */}}
function startProgressPolling(){stopProgressPolling();void tickProgress();progressTimer=window.setInterval(()=>{void tickProgress()},1000)}
async function runImport(){const file=importFile.value||createInlineImportFile(importText.value);if(!file.size){importError.value=new ApiError('请选择文件或输入英文单词');return}const ext=file.name.split('.').pop()?.toLowerCase();const mimeByExt:Record<string,string[]>={txt:['','text/plain'],csv:['','text/csv','application/csv','application/vnd.ms-excel'],json:['','application/json','text/json']};if(!ext||!mimeByExt[ext]){importError.value=new ApiError('请选择 TXT、CSV 或 JSON 文件');return}if(!mimeByExt[ext].includes(file.type)){importError.value=new ApiError(`文件类型 ${file.type||'未知'} 与 .${ext} 扩展名不匹配`);return}if(file.size>10*1024*1024){importError.value=new ApiError('文件不能超过 10 MB');return}const tags=importTags.value.split(/[,，]/).map(s=>s.trim()).filter(Boolean);importing.value=true;importError.value=null;try{const result=await startImport(file,{conflictPolicy:importPolicy.value,unresolvedPolicy:importUnresolvedPolicy.value,dryRun:importDryRun.value,tags});if(importDryRun.value){importResult.value=result as ImportSummary}else{importOpen.value=false;importResult.value=null;startImportPolling()}}catch(e){importError.value=normalizeApiError(e)}finally{importing.value=false}}
function stopImportPolling(){if(importPollTimer!==undefined){window.clearInterval(importPollTimer);importPollTimer=undefined}}
async function tickImport(){try{const p=await listImportProgress();importProgress.value=p;if(p.state==='idle'&&p.finished){stopImportPolling();const failed=p.failed?`，失败 ${p.failed}`:'';ElMessage.success(`导入完成:新增 ${p.created}，更新 ${p.updated}，跳过 ${p.skipped}${failed}，未命中 ${p.unresolved}`);await load()}}catch{/* 静默 */}}
function startImportPolling(){stopImportPolling();void tickImport();importPollTimer=window.setInterval(()=>{void tickImport()},800)}
function onFile(event:Event){const files=(event.target as HTMLInputElement).files;importFile.value=files?.[0]||null;importResult.value=null;importError.value=null}
function useJsonTemplate(){importText.value=jsonTemplate;importFile.value=null;importResult.value=null;importError.value=null;jsonTemplateOpen.value=false}
function batchItems():BatchItem[]{return selectedWords.value.map(w=>({id:w.id,expected_version:w.version}))}
function clearSelection(){selectedWords.value=[];wordListRef.value?.clearSelection()}
async function doBatchDelete(){if(!selectedWords.value.length)return;try{await ElMessageBox.confirm(`将软删除选中的 ${selectedWords.value.length} 个单词，历史记录仍会保留。`,'确认批量删除',{confirmButtonText:'删除',cancelButtonText:'取消',type:'warning'})}catch{return}batchBusy.value=true;try{const r=await batchDeleteWords(batchItems());ElMessage.success(`已删除 ${r.deleted.length} 个`);if(r.conflicts.length||r.missing.length)ElMessage.warning(`${r.conflicts.length+r.missing.length} 个已变化或不存在，已跳过`);clearSelection();await load()}catch(e){ElMessage.error(normalizeApiError(e).message)}finally{batchBusy.value=false}}
async function doBatchTags(){const tags=batchTagInput.value.split(/[,，]/).map(s=>s.trim()).filter(Boolean);if(!tags.length){ElMessage.warning('请输入至少一个标签');return}batchBusy.value=true;try{const r=await batchSetTags(batchItems(),tags);ElMessage.success(`已给 ${r.updated.length} 个单词加标签`);if(r.conflicts.length||r.missing.length)ElMessage.warning(`${r.conflicts.length+r.missing.length} 个已变化或不存在，已跳过`);batchTagOpen.value=false;batchTagInput.value='';clearSelection();await load()}catch(e){ElMessage.error(normalizeApiError(e).message)}finally{batchBusy.value=false}}
async function doBatchAudio(){if(!selectedWords.value.length)return;batchAudioBusy.value=true;try{const r=await batchGenerateAudio(selectedWords.value.map(w=>w.id));ElMessage.success(`已加入音频队列 ${r.queued} 个`);startProgressPolling();clearSelection()}catch(e){ElMessage.error(normalizeApiError(e).message)}finally{batchAudioBusy.value=false}}
async function doBatchReset(){if(!selectedWords.value.length)return;try{await ElMessageBox.confirm(`将清空选中的 ${selectedWords.value.length} 个单词的复习记录(设为新词)。`,'确认设为新词',{confirmButtonText:'清空并设为新词',cancelButtonText:'取消',type:'warning'})}catch{return}batchBusy.value=true;try{const r=await batchResetProgress(selectedWords.value.map(w=>w.id));ElMessage.success(`已设为新词 ${r.reset} 个`);clearSelection();await load()}catch(e){ElMessage.error(normalizeApiError(e).message)}finally{batchBusy.value=false}}
const pageCount=computed(()=>Math.max(1,Math.ceil(total.value/(filters.size||20))))
const importPercent=()=>{const p=importProgress.value;if(!p||!p.total)return 0;return Math.round((p.processed/p.total)*100)}
</script>
<template><section class="page"><div class="page-heading"><div><p class="eyebrow">VOCABULARY</p><p>共 {{ total }} 个单词，筛选条件会保存在地址栏。</p></div><div class="button-row"><el-button class="mobile-filter" @click="filterOpen=true">筛选</el-button><el-button :loading="batchAudioLoading" @click="generateMissingAudio">一键生成音频</el-button><el-button :loading="regeneratingAll" @click="regenerateAll">全部重新生成</el-button><el-button :loading="generatingNumbers" @click="generateNumbersAudio">生成序号音频(1–50)</el-button><el-button @click="importOpen=true">导入 / 导出</el-button><el-button type="primary" @click="openCreate">新增单词</el-button></div></div>
  <div v-if="audioProgress&&audioProgress.total>0" class="panel audio-progress" role="status" aria-live="polite">
    <div class="audio-progress-head"><strong>音频后台生成中</strong><span class="muted">{{ audioProgress.completed + audioProgress.failed }} / {{ audioProgress.total }}{{ audioProgress.failed?` · 失败 ${audioProgress.failed}`:'' }}{{ audioProgress.state==='idle'?' · 已完成':'' }}</span></div>
    <el-progress :percentage="audioProgressPercent()" :status="audioProgress.state==='idle'?(audioProgress.failed?'warning':'success'):undefined" :stroke-width="14" />
  </div>
  <div v-if="importProgress&&importProgress.total>0" class="panel import-progress" role="status" aria-live="polite">
    <div class="audio-progress-head"><strong>{{ importProgress.state==='running'?'导入后台进行中':'导入已完成' }}</strong><span class="muted">{{ importProgress.processed }} / {{ importProgress.total }}{{ importProgress.failed?` · 失败 ${importProgress.failed}`:'' }}</span><el-button link size="small" @click="importProgress=null">关闭</el-button></div>
    <el-progress :percentage="importPercent()" :status="importProgress.state==='idle'?(importProgress.failed?'warning':'success'):undefined" :stroke-width="14" />
    <div class="import-tally"><span>新增 <b>{{ importProgress.created }}</b></span><span>更新 <b>{{ importProgress.updated }}</b></span><span>跳过 <b>{{ importProgress.skipped }}</b></span><span>未命中 <b>{{ importProgress.unresolved }}</b></span></div>
    <div v-if="importProgress.unresolved_words?.length" class="unresolved-box"><strong>以下 {{ importProgress.unresolved_words.length }} 个单词未命中词典，未导入：</strong><span class="unresolved-words">{{ importProgress.unresolved_words.join('、') }}</span></div>
  </div>
  <div v-if="selectedWords.length" class="panel batch-bar"><span class="batch-count">已选 {{ selectedWords.length }} 项</span><el-button size="small" @click="batchTagOpen=true">加标签</el-button><el-button size="small" :loading="batchAudioBusy" @click="doBatchAudio">生成音频</el-button><el-button size="small" :loading="batchBusy" @click="doBatchReset">设为新词</el-button><el-button size="small" type="danger" :loading="batchBusy" @click="doBatchDelete">删除</el-button><el-button size="small" link @click="clearSelection">取消选择</el-button></div>
  <div class="panel filters desktop-filters"><el-input v-model="filters.keyword" clearable placeholder="搜索英文或中文" aria-label="搜索英文或中文"/><el-input :model-value="filters.tag?.join(', ')" clearable placeholder="标签，逗号分隔" aria-label="标签筛选" @update:model-value="setTags"/><el-select v-model="filters.is_custom" clearable placeholder="全部类型" aria-label="自定义词筛选"><el-option label="自定义词" :value="true"/><el-option label="普通词" :value="false"/></el-select><input v-model="filters.created_from" class="filter-input" type="date" aria-label="创建开始日期"/><input v-model="filters.created_to" class="filter-input" type="date" aria-label="创建结束日期"/><el-select v-model="filters.sort" aria-label="排序"><el-option label="最新创建" value="created_at_desc"/><el-option label="最早创建" value="created_at_asc"/><el-option label="英文 A–Z" value="en_word_asc"/><el-option label="英文 Z–A" value="en_word_desc"/></el-select></div>
  <div class="panel"><AsyncState :phase="state.phase.value" :error="state.error.value" empty-text="词库还是空的，先加入第一个单词吧。" @retry="load"><template #empty-action><el-button type="primary" @click="openCreate">新增单词</el-button></template><ResponsiveWordList v-if="state.data.value" ref="wordListRef" :words="state.data.value" @edit="openEdit" @remove="remove" @reset="resetProgress" @play-audio="playAudio" @generate-audio="generateAudio" @review="word=>$router.push({path:'/history',query:{word_id:word.id}})" @selection-change="(w:Word[])=>selectedWords=w"/><div v-if="pageCount>1" class="pagination"><el-pagination v-model:current-page="filters.page" layout="prev, pager, next" :page-count="pageCount"/></div></AsyncState></div>
  <WordEditorDialog v-model="editorOpen" :word="editing" :submitting="submitting" :error="writeError" @submit="save"/>
  <el-drawer v-model="filterOpen" title="筛选单词" size="90%"><div class="drawer-filters"><el-input v-model="filters.keyword" clearable placeholder="搜索英文或中文"/><el-input :model-value="filters.tag?.join(', ')" clearable placeholder="标签，逗号分隔" @update:model-value="setTags"/><el-select v-model="filters.is_custom" clearable placeholder="全部类型"><el-option label="自定义词" :value="true"/><el-option label="普通词" :value="false"/></el-select><label>创建开始日期<input v-model="filters.created_from" class="filter-input" type="date"/></label><label>创建结束日期<input v-model="filters.created_to" class="filter-input" type="date"/></label><el-select v-model="filters.sort"><el-option label="最新创建" value="created_at_desc"/><el-option label="最早创建" value="created_at_asc"/><el-option label="英文 A–Z" value="en_word_asc"/><el-option label="英文 Z–A" value="en_word_desc"/></el-select><el-button type="primary" @click="filterOpen=false">查看结果</el-button></div></el-drawer>
  <el-dialog v-model="importOpen" title="导入与导出" width="min(620px, calc(100vw - 24px))">
    <div class="import-title-row"><div><h3>只输入英文，自动生成词条</h3><p class="muted">每行一个英文单词，或选择 .txt 文件；也兼容完整字段的 CSV / JSON。真导入在后台进行，单个失败不阻断。</p></div><el-button @click="jsonTemplateOpen=true">查看 JSON 字段模板</el-button></div>
    <el-input v-model="importText" type="textarea" :rows="6" placeholder="每行一个英文单词，或粘贴 JSON 字段模板" aria-label="英文单词列表或 JSON 模板"/><div class="import-or">或者选择文件</div><input class="file-input" type="file" accept=".txt,.csv,.json,text/plain,text/csv,application/json" @change="onFile"/>
    <p class="muted import-label">默认标签（逗号分隔，会并入每一行导入的单词）</p><el-input v-model="importTags" clearable placeholder="例如：基础, 词汇" aria-label="默认标签"/>
    <el-radio-group v-model="importPolicy"><el-radio-button value="reject">冲突即拒绝</el-radio-button><el-radio-button value="skip">跳过重复</el-radio-button><el-radio-button value="update">更新重复</el-radio-button></el-radio-group>
    <p class="muted import-label">词典未命中的单词（查不到且未填中文释义）：</p><el-radio-group v-model="importUnresolvedPolicy"><el-radio-button value="skip">跳过未命中</el-radio-button><el-radio-button value="ai">AI 补充</el-radio-button><el-radio-button value="reject">未命中即拒绝</el-radio-button></el-radio-group><el-checkbox v-model="importDryRun">仅校验，不写入</el-checkbox>
    <div v-if="importError" class="error-box" role="alert"><strong>本次零写入。</strong> {{ importError.message }}<span v-if="importError.requestId" class="request-id">请求编号：{{ importError.requestId }}</span></div><dl v-if="importResult" class="import-summary"><div><dt>新增</dt><dd>{{ importResult.created }}</dd></div><div><dt>更新</dt><dd>{{ importResult.updated }}</dd></div><div><dt>跳过</dt><dd>{{ importResult.skipped }}</dd></div><div><dt>未命中</dt><dd>{{ importResult.unresolved||0 }}</dd></div><div><dt>词典命中</dt><dd>{{ importResult.dictionary_matches||0 }}</dd></div><div><dt>总计</dt><dd>{{ importResult.total }}</dd></div></dl><div v-if="importResult?.unresolved_words?.length" class="unresolved-box" role="status"><strong>以下 {{ importResult.unresolved_words.length }} 个单词未命中词典，未导入：</strong><span class="unresolved-words">{{ importResult.unresolved_words.join('、') }}</span><p class="muted">可改用 CSV / JSON 并为它们补上 cn_meaning 后重新导入。</p></div>
    <el-button type="primary" :loading="importing" :disabled="!importFile&&!importText.trim()" @click="runImport">{{ importDryRun?'开始校验':'开始导入' }}</el-button><el-divider/><h3>导出当前筛选范围</h3><div class="button-row"><el-button @click="exportWords('csv',filters)">导出 CSV</el-button><el-button @click="exportWords('json',filters)">导出 JSON</el-button></div>
  </el-dialog>
  <el-dialog v-model="batchTagOpen" title="批量加标签" width="min(420px, calc(100vw - 24px))"><p class="muted">为选中的 {{ selectedWords.length }} 个单词追加标签（并集，不覆盖已有标签）。</p><el-input v-model="batchTagInput" placeholder="标签，逗号分隔" aria-label="批量标签"/><template #footer><el-button @click="batchTagOpen=false">取消</el-button><el-button type="primary" :loading="batchBusy" @click="doBatchTags">确认</el-button></template></el-dialog>
  <el-dialog v-model="jsonTemplateOpen" title="JSON 导入字段模板" width="min(680px, calc(100vw - 24px))" append-to-body><p class="muted">文件顶层必须是数组。只有 <code>en_word</code> 必填；其余字段可由本地词典或 AI 补充。可以保存为 .json 文件，也可以直接使用模板导入。</p><pre class="json-template">{{ jsonTemplate }}</pre><template #footer><el-button @click="jsonTemplateOpen=false">关闭</el-button><el-button type="primary" @click="useJsonTemplate">使用此模板</el-button></template></el-dialog>
</section></template>
<style scoped>.filters{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px}.mobile-filter{display:none}.audio-progress{display:grid;gap:8px}.import-progress{display:grid;gap:10px}.audio-progress-head{display:flex;justify-content:space-between;align-items:baseline;gap:10px}.audio-progress .muted{font-size:.82rem}.import-tally{display:flex;gap:18px;flex-wrap:wrap;color:var(--muted);font-size:.85rem}.import-tally b{color:var(--ink);font-size:1.05rem;margin-left:4px}.batch-bar{display:flex;align-items:center;gap:10px;flex-wrap:wrap;background:var(--green-100);border:1px solid var(--green-300,#9fceb3)}.batch-count{font-weight:700;margin-right:auto;color:var(--green-800)}.drawer-filters{display:grid;gap:14px}.drawer-filters label{display:grid;gap:6px;color:var(--muted);font-size:.85rem}.filter-input{width:100%;min-height:40px;padding:0 11px;border:1px solid #dcdfe6;border-radius:4px;background:#fff;color:var(--ink)}.file-input{display:block;width:100%;min-height:48px;margin:10px 0}.import-title-row{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.import-title-row h3,.import-title-row p{margin-top:0}.json-template{max-height:55vh;overflow:auto;padding:16px;border:1px solid var(--line);border-radius:10px;background:#f5f7fa;white-space:pre-wrap;font:13px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace}.import-or{text-align:center;color:var(--muted);font-size:.8rem;margin-top:10px}.import-label{font-size:.78rem;margin:10px 0 4px}.unresolved-box{margin-top:10px;padding:10px 12px;background:var(--yellow-100,#fff7e6);border:1px solid var(--yellow-300,#ffd591);border-radius:8px;font-size:.85rem}.unresolved-box .unresolved-words{display:block;margin:6px 0 4px;color:var(--ink);word-break:break-all}.import-summary{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.import-summary div{padding:10px;text-align:center;background:var(--green-100);border-radius:8px}.import-summary dt{font-size:.75rem;color:var(--muted)}.import-summary dd{margin:4px 0 0;font-weight:800}@media(max-width:639px){.desktop-filters{display:none}.mobile-filter{display:inline-flex}.import-title-row{display:grid}.import-summary{grid-template-columns:repeat(3,1fr)}}</style>
